# Generated by Django 6.0.6 on 2026-07-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('gaming_hours', models.FloatField()),
                ('study_hours', models.FloatField()),
                ('sleep_hours', models.FloatField()),
                ('attendance', models.FloatField()),
                ('gaming_genre', models.CharField(max_length=20)),
                ('social_activity', models.FloatField()),
                ('device_usage', models.FloatField()),
                ('reaction_time_ms', models.FloatField()),
                ('addiction_score', models.FloatField()),
                ('stress_level', models.CharField(max_length=10)),
                ('grades', models.FloatField()),
            ],
        ),
    ]
